### ISSUE TITLE
[Error 13] Permission denied

### ISSUE THREAD

**Issue by prenone** [neilenns/PlatformIO-Template#3]
Hello,
I am running a (kind of) fresh installation of Fedora Linux 35 and I am trying to program an Arduino Zero equivalent board.
I know that the board itself is not the problem as I am able to program it using PlatformIo on another computer (Windows 10 based).
I am not able to connect to the board (I tried upload and monitor) as I get the following error:
`could not open port '/dev/ttyACM0': [Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'`.
Has anybody ever encountered a similiar issue or maybe knows what I am doing wrong?
Thanks

**Comment by neilenns** [comment]
This git repo isn't a support forum for PlatformIO development. I suggest posting your question to the PlatformIO forums here: https://community.platformio.org/
